In [2]:
"""
-----------------------------------------------------------------------------
Matrix computation exercise using python and numpy
-----------------------------------------------------------------------------
AUTHOR: Soumitra Samanta (soumitra.samanta@gm.rkmvu.ac.in)
-----------------------------------------------------------------------------
Package required:
Numpy: https://numpy.org/
Matplotlib: https://matplotlib.org
-----------------------------------------------------------------------------
"""

import numpy as np
from numpy.random import RandomState

from typing import Tuple

np.random.seed(42)# To reproduce the random numbers


# Generate a random vector $x \in \mathbf{R}^{n}$ contains intergers between $[-l, l]$.
[3 points]

In [3]:
n = 10
l = 9
x = []
############################################################################
#                             Your code will be here                       #
#--------------------------------------------------------------------------#
x = np.random.randint(-l, l, n)

#--------------------------------------------------------------------------#
#                             End of your code                             #
############################################################################

print('A random vector of size {}: ' .format(n))
print('-'*70)
print('x: {}' .format(x))
print('-'*70)

A random vector of size 10: 
----------------------------------------------------------------------
x: [-3  5  1 -2 -3  1  1 -6 -2 -7]
----------------------------------------------------------------------


# Write a function to calculate the 'dot' product between two vectors. Generate two random vectors $x, y \in \mathbf{R}^{n}$ contains intergers between $[-l, l]$ and find the dot product between $x$ and $y$ (your function should handle different order vectors). Check your result with the [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html).
[5 points]




In [4]:
n = 10
l = 9
x = []
y = []

def vector_dot_product(
    x: np.array,
    y: np.array,
)->float:
    """
    Dot product between two vectors
    
    Inputs:
        - x: 1st vector
        - y: 2nd vector
       
    Output:
        - val: Dot product between x and y
    
    """
    
    val = 0
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    
    if (len(x) == len(y)):
        for i in range(len(x)):
            val += (x[i] * y[i])
    else:
        raise ValueError("Error in Input")
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
    
    return val

# np.random.seed(42)# for reproduce the random numbers
x = np.random.randint(-l,l,n)
y = np.random.randint(-l,l,n)

print('Two random vectors of size {} are:' .format(n))
print('-'*70)
print('x: {}\nand \ny: {}' .format(x, y))
print('-'*70)

val = vector_dot_product(x, y)
print('The dot product between x and y is: {}' .format(val))
print('-'*70)

Two random vectors of size 10 are:
----------------------------------------------------------------------
x: [-8  2 -4 -8 -9  2  2  7  0  6]
and 
y: [ 5  5  2 -7 -5 -3 -1 -3  8 -6]
----------------------------------------------------------------------
The dot product between x and y is: -2
----------------------------------------------------------------------


# Generate a random matrix $A$ of size $m \times n$ contains intergers between $[-l, l]$.
[2 points]

In [5]:
m = 3
n = 5
l = 9
A = []
############################################################################
#                             Your code will be here                       #
#--------------------------------------------------------------------------#
A = np.random.randint(-l, l, size = (m,n))
#--------------------------------------------------------------------------#
#                             End of your code                             #
############################################################################

print('A random matrix of size {}x{} A:\n{}: ' .format(m, n, A))
print('-'*70)



A random matrix of size 3x5 A:
[[ 4  8 -1 -8  5]
 [-3  2 -2  5 -7]
 [ 4  7 -6  8 -2]]: 
----------------------------------------------------------------------


# Write a function to calculate the product of two matrices. Generate two random matrices $x \in \mathbf{R}^{m \times n}$ and $y \in \mathbf{R}^{n \times m}$ contains intergers between $[-l, l]$ and find the product of of $x$ and $y$ (your function should handle different order matrices). Check your result with the [numpy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) or [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html).

[10 points]




In [6]:
m = 3
n = 5
l = 9
x = []
y = []

def matrix_multiplication(
    x: np.array,
    y: np.array,
)->np.array:
    """
    Dot product between two vectors
    
    Inputs:
        - x: 1st matrix
        - y: 2nd matrix
       
    Output:
        - val: multiplication x and y
    
    """
    
    val =  np.zeros((x.shape[0],y.shape[1]))
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    if (x.shape[1] == y.shape[0]):
        for i in range(x.shape[0]):
            for j in range(y.shape[1]):
                for k in range(y.shape[0]):
                    val[i][j] += x[i][k] * y[k][j]

    else:
        raise ValueError("Dimension Problem")
            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
    
    return val

# np.random.seed(42)# for reproduce the random numbers
A = np.random.randint(-l, l, size = (m,n))
B = np.random.randint(-l, l, size = (n,m))

print('Two random matrices are:')
print('A: \n{}\nand\nB: \n{}' .format(A, B))
print('-'*70)

val = matrix_multiplication(A, B)
print('The multiplication of A and B using my function is: \n{}' .format(val))
print('-'*70)

val1 = np.matmul(A, B)
print('The multiplication of A and B using numpy.matmul is: \n{}' .format(val1))
print('-'*70)

val1 = np.dot(A, B)
print('The multiplication of A and B using numpy.dot is: \n{}' .format(val1))
print('-'*70)


Two random matrices are:
A: 
[[-6 -8 -4  0 -6]
 [ 8  2 -8  0 -6]
 [ 4  6  5 -2  4]]
and
B: 
[[-2  6  3]
 [ 8  5  3]
 [-1  5  3]
 [-9 -3 -1]
 [-9  2 -2]]
----------------------------------------------------------------------
The multiplication of A and B using my function is: 
[[   6. -108.  -42.]
 [  62.    6.   18.]
 [  17.   93.   39.]]
----------------------------------------------------------------------
The multiplication of A and B using numpy.matmul is: 
[[   6 -108  -42]
 [  62    6   18]
 [  17   93   39]]
----------------------------------------------------------------------
The multiplication of A and B using numpy.dot is: 
[[   6 -108  -42]
 [  62    6   18]
 [  17   93   39]]
----------------------------------------------------------------------


# Implement elementary row operations and check your script with a random example.
[15 points]

In [52]:
def elementary_ops_interchange_rows(
    A: np.array, 
    ith_row: int, 
    jth_row: int
)->np.array:
    """
    Elementary row operation: interchange i-th and j-th rows
    
     Inputs:
        - A: Given matrix
        - ith_row: i-th row
        - jth_row: j-th row
        
    Output:
        - A: Resultant rows interchhanged matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    t = np.copy( A[jth_row-1,:])
    A[jth_row-1,:] = A[ith_row-1,:]
    A[ith_row-1,:] = t
    #A[[ith_row-1, jth_row-1]] = A[[jth_row-1, ith_row-1]]
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A


def elementary_ops_scale_row(
    A: np.array, 
    ith_row: int, 
    scalar_val: float
)->np.array:
    """
    Elementary row operation: Scaling i-th row  with the scalar_val value
    
     Inputs:
        - A: Given matrix
        - ith_row: row want to scale
        - scalar_val: scalar value
        
    Output:
        - A: Resultant row scaling matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    A[ith_row-1,:] = scalar_val * A[ith_row-1,:]
            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A

def elementary_ops_change_row(
    A: np.array, 
    ith_row: int, 
    jth_row: int,
    scalar_val: float
)->np.array:
    """
    Elementary row operation: Change i-th based on i<-i + scalar_val*j
    
     Inputs:
        - A: Given matrix
        - ith_row: i-th row
        - jth_row: j-th row
        - scalar_val: scalar value
        
    Output:
        - A: Resultant row updated matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    A[ith_row-1,:] = A[jth_row-1,:] * scalar_val + A[ith_row-1,:]
    
            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A

def elementary_ops_interchange_rows_mult(
    A: np.array, 
    ith_row: int, 
    jth_row: int
)->Tuple[np.array, np.array]:
    """
    Elementary row operation: interchange i-th and j-th rows
    
     Inputs:
        - A: Given matrix
        - ith_row: i-th row
        - jth_row: j-th row
        
    Output:
        - A: Resultant rows interchhanged matrix
    """
    I = np.eye(m)
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    I = elementary_ops_interchange_rows(I, i, j)
    A = matrix_multiplication(I,A)
    
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A, I


def elementary_ops_scale_row_mult(
    A: np.array, 
    ith_row: int, 
    scalar_val: float
)->Tuple[np.array, np.array]:
    """
    Elementary row operation: Scaling i-th row  with the scalar_val value
    
     Inputs:
        - A: Given matrix
        - ith_row: row want to scale
        - scalar_val: scalar value
        
    Output:
        - A: Resultant row scaling matrix
    """
    
    I = np.eye(m)
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    I = elementary_ops_scale_row(I, i, scalar)
    A = matrix_multiplication(I,A)
            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A, I

def elementary_ops_change_row_mult(
    A: np.array, 
    ith_row: int, 
    jth_row: int,
    scalar_val: float
)->Tuple[np.array, np.array]:
    """
    Elementary row operation: Change i-th based on i<-i + scalar_val*j
    
     Inputs:
        - A: Given matrix
        - ith_row: i-th row
        - jth_row: j-th row
        - scalar_val: scalar value
        
    Output:
        - A: Resultant row updated matrix
    """
    
    I = np.eye(m)
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    I = elementary_ops_change_row(I, i, j, scalar)
    A = matrix_multiplication(I,A)
            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A, I




np.random.seed(42)# for reproduce the random numbers
m = 3
n = 5
A = np.random.randint(1, 30, size = (m,n))

print('A random matrices A:\n{}' .format(A))
print('-'*70)
i = 1
j = 2
scalar = 3
E_ij = elementary_ops_interchange_rows(np.copy(A), i, j)
print('Elementary row operation: interchange {}-th and {}-th rows on A: \n{}' .format(i, j, E_ij))
print('-'*70)

E_i = elementary_ops_scale_row(np.copy(A), i, scalar)
print('Elementary row operation: Scaling {}-th row  with the {} value on A: \n{}' .format(i, scalar, E_i))
print('-'*70)

E_ij_scalar = elementary_ops_change_row(np.copy(A), i, j, scalar)
print('Elementary row operation: Change {}-th based on {}<-{} + {}*{} on A: \n{}' .format(i, i, i, scalar, j, E_ij_scalar))
print('-'*70)
E_ij,I_ij = elementary_ops_interchange_rows_mult(A, i, j)
print('Elementary row operation : interchange {}-th and {}-th rows on A: \n{}I_ij: \n{}' .format(i, j, E_ij,I_ij)) 
print('-'*70)
E_i,I_i = elementary_ops_scale_row_mult(A,i,scalar)
print('Elementary row operation : Scaling {}-th row  with the {} value on A: \n{}I_i: \n{}'.format(i,scalar,E_i,I_i))
print('-'*70)
E_ij_scalar,I_ij_scalar =  elementary_ops_change_row_mult(A,i,j,scalar)
print('Elementary row operation: Change {}-th based on {}<-{} + {}*{} on A: \n{} I_ij_scalar :\n{}' .format(i, i, i, scalar, j, E_ij_scalar,I_ij_scalar))
print('-'*70)


A random matrices A:
[[ 7 20 29 15 11]
 [ 8 29 21  7 26]
 [19 23 11 11 24]]
----------------------------------------------------------------------
Elementary row operation: interchange 1-th and 2-th rows on A: 
[[ 8 29 21  7 26]
 [ 7 20 29 15 11]
 [19 23 11 11 24]]
----------------------------------------------------------------------
Elementary row operation: Scaling 1-th row  with the 3 value on A: 
[[21 60 87 45 33]
 [ 8 29 21  7 26]
 [19 23 11 11 24]]
----------------------------------------------------------------------
Elementary row operation: Change 1-th based on 1<-1 + 3*2 on A: 
[[ 31 107  92  36  89]
 [  8  29  21   7  26]
 [ 19  23  11  11  24]]
----------------------------------------------------------------------
Elementary row operation : interchange 1-th and 2-th rows on A: 
[[ 8. 29. 21.  7. 26.]
 [ 7. 20. 29. 15. 11.]
 [19. 23. 11. 11. 24.]]I_ij: 
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
----------------------------------------------------------------------
Elementary row

# Implement elementary column operations and check your script with random example
[10 points]

In [53]:
def elementary_ops_interchange_cols(
    A: np.array, 
    ith_col: int, 
    jth_col: int
)->np.array:
    """
    Elementary col operation: interchange i-th and j-th cols
    
     Inputs:
        - A: Given matrix
        - ith_col: i-th col
        - jth_col: j-th col
        
    Output:
        - A: Resultant cols interchhanged matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    t = np.copy( A[:,j-1])
    A[:,j-1] = A[:,i-1]
    A[:,i-1] = t    
    
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A


def elementary_ops_scale_col(
    A: np.array, 
    ith_col: int, 
    scalar_val: float
)->np.array:
    """
    Elementary col operation: Scaling i-th col  with the scalar_val value
    
     Inputs:
        - A: Given matrix
        - ith_col: col want to scale
        - scalar_val: scalar value
        
    Output:
        - A: Resultant col scaling matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    A[:,ith_col-1] = scalar_val * A[:,ith_col-1]
            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A

def elementary_ops_change_col(
    A: np.array, 
    ith_col: int, 
    jth_col: int,
    scalar_val: float
)->np.array:
    """
    Elementary col operation: Change i-th col based on i<-i + scalar_val*j
    
     Inputs:
        - A: Given matrix
        - ith_col: i-th col
        - jth_col: j-th col
        - scalar_val: scalar value
        
    Output:
        - A: Resultant col updated matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    A[:,ith_col-1] = A[:,jth_col-1] * scalar_val + A[:,ith_col-1]
            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A

def elementary_ops_interchange_cols_mult(
    A: np.array, 
    ith_col: int, 
    jth_col: int
)->np.array:
    """
    Elementary col operation: interchange i-th and j-th cols
    
     Inputs:
        - A: Given matrix
        - ith_col: i-th col
        - jth_col: j-th col
        
    Output:
        - A: Resultant cols interchhanged matrix
    """
    
    I = np.eye(n)
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    I = elementary_ops_interchange_cols(I, i, j)
    A = matrix_multiplication(A,I)
    
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A, I


def elementary_ops_scale_col_mult(
    A: np.array, 
    ith_col: int, 
    scalar_val: float
)->Tuple[np.array, np.array]:
    """
    Elementary col operation: Scaling i-th col  with the scalar_val value
    
     Inputs:
        - A: Given matrix
        - ith_col: col want to scale
        - scalar_val: scalar value
        
    Output:
        - A: Resultant col scaling matrix
    """
    
    I = np.eye(n)
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    I = elementary_ops_scale_col(I, i, scalar)
    A = matrix_multiplication(A,I)
            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A, I

def elementary_ops_change_col_mult(
    A: np.array, 
    ith_col: int, 
    jth_col: int,
    scalar_val: float
)->Tuple[np.array, np.array]:
    """
    Elementary col operation: Change i-th col based on i<-i + scalar_val*j
    
     Inputs:
        - A: Given matrix
        - ith_col: i-th col
        - jth_col: j-th col
        - scalar_val: scalar value
        
    Output:
        - A: Resultant col updated matrix
    """
    
    I = np.eye(n)
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    I = elementary_ops_change_col(I, i, j, scalar)
    A = matrix_multiplication(A,I)       
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A, I


np.random.seed(42)# for reproduce the random numbers
m = 3
n = 5
A = np.random.randint(1, 40, size = (m,n))

print('A random matrices A:\n{}' .format(A))
print('-'*70)
i = 1
j = 2
scalar = 3
E_ij = elementary_ops_interchange_cols(np.copy(A), i, j)
print('Elementary col operation: interchange {}-th and {}-th cols on A: \n{}' .format(i, j, E_ij))
print('-'*70)

E_i = elementary_ops_scale_col(np.copy(A), i, scalar)
print('Elementary col operation: Scaling {}-th col  with the {} value on A: \n{}' .format(i, scalar, E_i))
print('-'*70)

E_ij_scalar = elementary_ops_change_col(np.copy(A), i, j, scalar)
print('Elementary col operation: Change {}-th based on {}<-{} + {}*{} on A: \n{}' .format(i, i, i, scalar, j, E_ij_scalar))
print('-'*70)

E_ij,I_ij = elementary_ops_interchange_cols_mult(np.copy(A), i, j)
print('Elementary col  operation : interchange {}-th and {}-th cols on A: \n{}I_ij: \n{}' .format(i, j, E_ij,I_ij)) 
print('-'*70)
E_i,I_i = elementary_ops_scale_col_mult(A,i,scalar)
print('Elementary col operation : Scaling {}-th col  with the {} value on A: \n{}I_i: \n{}'.format(i,scalar,E_i,I_i))
print('-'*70)
E_ij_scalar,I_ij_scalar =  elementary_ops_change_col_mult(A,i,j,scalar)
print('Elementary col operation: Change {}-th based on {}<-{} + {}*{} on A: \n{} I_ij_scalar :\n{}' .format(i, i, i, scalar, j, E_ij_scalar,I_ij_scalar))
print('-'*70)


A random matrices A:
[[39 29 15  8 21]
 [39 19 23 11 11]
 [24 36 24  3 22]]
----------------------------------------------------------------------
Elementary col operation: interchange 1-th and 2-th cols on A: 
[[29 39 15  8 21]
 [19 39 23 11 11]
 [36 24 24  3 22]]
----------------------------------------------------------------------
Elementary col operation: Scaling 1-th col  with the 3 value on A: 
[[117  29  15   8  21]
 [117  19  23  11  11]
 [ 72  36  24   3  22]]
----------------------------------------------------------------------
Elementary col operation: Change 1-th based on 1<-1 + 3*2 on A: 
[[126  29  15   8  21]
 [ 96  19  23  11  11]
 [132  36  24   3  22]]
----------------------------------------------------------------------
Elementary col  operation : interchange 1-th and 2-th cols on A: 
[[29. 39. 15.  8. 21.]
 [19. 39. 23. 11. 11.]
 [36. 24. 24.  3. 22.]]I_ij: 
[[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
---------------

# Implement row and column sweep out and check your script with random example
[10 points]

In [54]:
def sweep_out_row(
    A: np.array,
    ith_row: int,
    pivot_element: Tuple[int, int]
)->np.array:
    """
    Sweep out a i-th row based on the given pivot element
    
    Inputs:
        - A: Given matrix
        - ith_row: row to sweep out
        - pivot_element pivot element
        
    Output:
        - A: Resultant row sweep out matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    if pivot_element[0] != ith_row:
        raise ValueError ("pivot element position not in the given row ")
    elif A[pivot_element[0]-1,pivot_element[1]-1]==0:
        raise ValueError("pivot element is zero,sweeping cannot be done")
    else:
        A[:,pivot_element[1]-1]=A[:,pivot_element[1]-1]/A[pivot_element[0]-1,pivot_element[1]-1]
        for k in range (A.shape[1]):
            if k != pivot_element[1]-1 and A[pivot_element[0]-1,k]!=0:
                A[:,k]=A[:,k]-A[ith_row-1,k]*A[:,pivot_element[1]-1]    
        
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
    
    return A
    
    
def sweep_out_col(
    A: np.array,
    ith_col: int,
    pivot_element: Tuple[int, int]
)->np.array:
    """
    Sweep out a i-th column based on the given pivot element
    
    Inputs:
        - A: Given matrix
        - ith_col: column to sweep out
        - pivot_element pivot element
        
    Output:
        - A: Resultant column sweep out matrix
    """
    
    ############################################################################
    #                             Your code will be here                       #

    #--------------------------------------------------------------------------#
    if pivot_element[1] != ith_col:
        raise ValueError ("pivot element position not in the given column ")
    elif A[pivot_element[0]-1,pivot_element[1]-1]==0:
        raise ValueError("pivot element is zero,sweeping cannot be done")
    else:
        A[pivot_element[0]-1,:]=A[pivot_element[0]-1,:]/A[pivot_element[0]-1,pivot_element[1]-1]
        for k in range (A.shape[0]):
            if k != pivot_element[0]-1 and A[k,pivot_element[1]-1]!= 0:
                A[k,:] = A[k,:]-A[k,ith_col-1]*A[pivot_element[0]-1,:]   
    
        
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
    
    return A



np.random.seed(42)# for reproduce the random numbers
m = 3
n = 5
A =np.random.randint(10, 30, size = (m,n))

print('A random matrices A:\n{}' .format(A))
print('-'*70)
i = 1
j = 2
scalar = 3
E_ij = sweep_out_row(np.copy(A), i, (i, j))
print('{}-th row sweep out based on ({}, {}) as pivot on A: \n{}' .format(i, i, j, E_ij))
print('-'*70)

E_ij = sweep_out_col(np.copy(A), j, (i, j))
print('{}-th col sweep out based on ({}, {}) as pivot on A: \n{}' .format(j, i, j, E_ij))
print('-'*70)


A random matrices A:
[[16 29 24 20 17]
 [16 28 20 20 13]
 [17 12 11 21 15]]
----------------------------------------------------------------------
1-th row sweep out based on (1, 2) as pivot on A: 
[[ 0  1  0  0  0]
 [16  0 20 20 13]
 [17  0 11 21 15]]
----------------------------------------------------------------------
2-th col sweep out based on (1, 2) as pivot on A: 
[[ 0  1  0  0  0]
 [16  0 20 20 13]
 [17  0 11 21 15]]
----------------------------------------------------------------------


# Implement reduced echelon form of a matrix $A$ 
[30 points]

In [55]:
def reduced_echelon_form(
    A: np.array
)-> np.array:
    """Reduction to echelon form of a matrix.
    
    Inputs:
        - A: Given matrix
        
    Output:
        - A: Echelon form of A
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    l=0
    for j in range(A.shape[1]):
        for i in range(A.shape[0]):
            if i+l < A.shape[0]:
                if A[i+l,j] != 0:
                    elementary_ops_interchange_rows(A,i+l+1,l+1)
                    print(A)
                    sweep_out_col(A,j+1,(l+1,j+1))
                    print(A)
                    l = l+1  
                        
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A
        
    
np.random.seed(42)# for reproduce the random numbers
m = 4
n = 5
#A = np.random.randint(-2,32,(4,5))
A = np.array([
    [0, 0, 0, 0, 5],
    [0, 2, -1, 3, -2],
    [0, -4, 2, -6, 4],
    [0, 6, -3, 8, 1]
]).astype(float)

print('A random matrices A:\n{}' .format(A))
print('-'*70)

EF_A = reduced_echelon_form(A) 
print('The reduced echelon form of A:\n{} ' .format(np.round(EF_A, 3)))
print('-'*70)
        
    

A random matrices A:
[[ 0.  0.  0.  0.  5.]
 [ 0.  2. -1.  3. -2.]
 [ 0. -4.  2. -6.  4.]
 [ 0.  6. -3.  8.  1.]]
----------------------------------------------------------------------
[[ 0.  2. -1.  3. -2.]
 [ 0.  0.  0.  0.  5.]
 [ 0. -4.  2. -6.  4.]
 [ 0.  6. -3.  8.  1.]]
[[ 0.   1.  -0.5  1.5 -1. ]
 [ 0.   0.   0.   0.   5. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.  -1.   7. ]]
[[ 0.   1.  -0.5  1.5 -1. ]
 [ 0.   0.   0.  -1.   7. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   5. ]]
[[ 0.   1.  -0.5  0.   9.5]
 [-0.  -0.  -0.   1.  -7. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   5. ]]
[[ 0.   1.  -0.5  0.   9.5]
 [-0.  -0.  -0.   1.  -7. ]
 [ 0.   0.   0.   0.   5. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.   1.  -0.5  0.   0. ]
 [ 0.   0.   0.   1.   0. ]
 [ 0.   0.   0.   0.   1. ]
 [ 0.   0.   0.   0.   0. ]]
The reduced echelon form of A:
[[ 0.   1.  -0.5  0.   0. ]
 [ 0.   0.   0.   1.   0. ]
 [ 0.   0.   0.   0.   1. ]
 [ 0.   0.   0.   0.   0. ]] 
------------

# Implement reduction to upper triangular form of a matrix $A$
[15 points]

In [56]:

def reduced_upper_triangular_form(
    A: np.array
)-> np.array:
    """Reduction to upper triangular form of a square matrix.
    
    Inputs:
        - A: Given matrix
        
    Output:
        - A: Upper triangular form of A
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    h = 0
    for j in range(A.shape[1]):
        for i in range(A.shape[0]):
            if (i + h) < A.shape[0]:
                if A[i + h, j] != 0:
                    elementary_ops_interchange_rows(A, i + h+1, h+1)
                    h += 1
    h = 0
    for j in range(A.shape[1]):
        for i in range(A.shape[0]):
            if i > j:
                if A[h,h]!=0:
                    #A[i, :] = A[i, :] / A[i,i]
                    A[i, :] = A[i, :] - (A[i, j]/A[h,h]) * A[h, :]
                    print(A)
            if i == A.shape[0]-1:
                h += 1    
    
        
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A

np.random.seed(42)# for reproduce the random numbers
n = 5
A = np.random.randint(5,10,size=(5,5))
print('A random matrices A:\n{}' .format(A))
print('-'*70)

UT_A = reduced_upper_triangular_form(A)        
print('The reduced upper triangular form of A:\n{} ' .format(np.round(UT_A, 3)))
print('-'*70)      






A random matrices A:
[[8 9 7 9 9]
 [6 7 7 7 9]
 [8 7 9 6 8]
 [6 8 9 5 8]
 [6 9 8 5 5]]
----------------------------------------------------------------------
[[ 8  9  7  9  9]
 [ 0 -2  2 -3 -1]
 [ 6  9  8  5  5]
 [ 6  8  9  5  8]
 [ 6  7  7  7  9]]
[[ 8  9  7  9  9]
 [ 0 -2  2 -3 -1]
 [ 0  2  2 -1 -1]
 [ 6  8  9  5  8]
 [ 6  7  7  7  9]]
[[ 8  9  7  9  9]
 [ 0 -2  2 -3 -1]
 [ 0  2  2 -1 -1]
 [ 0  1  3 -1  1]
 [ 6  7  7  7  9]]
[[ 8  9  7  9  9]
 [ 0 -2  2 -3 -1]
 [ 0  2  2 -1 -1]
 [ 0  1  3 -1  1]
 [ 0  0  1  0  2]]
[[ 8  9  7  9  9]
 [ 0 -2  2 -3 -1]
 [ 0  0  4 -4 -2]
 [ 0  1  3 -1  1]
 [ 0  0  1  0  2]]
[[ 8  9  7  9  9]
 [ 0 -2  2 -3 -1]
 [ 0  0  4 -4 -2]
 [ 0  0  4 -2  0]
 [ 0  0  1  0  2]]
[[ 8  9  7  9  9]
 [ 0 -2  2 -3 -1]
 [ 0  0  4 -4 -2]
 [ 0  0  4 -2  0]
 [ 0  0  1  0  2]]
[[ 8  9  7  9  9]
 [ 0 -2  2 -3 -1]
 [ 0  0  4 -4 -2]
 [ 0  0  0  2  2]
 [ 0  0  1  0  2]]
[[ 8  9  7  9  9]
 [ 0 -2  2 -3 -1]
 [ 0  0  4 -4 -2]
 [ 0  0  0  2  2]
 [ 0  0  0  1  2]]
[[ 8  9  7  9  9]
 [ 0 

In [63]:
def reduced_identity_form(
    A: np.array
)-> np.array:
    """Reduction to upper triangular form of a square matrix.
    
    Inputs:
        - A: Given matrix
        
    Output:
        - A: identity form of A
    """
    
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    l=0
    for j in range(A.shape[1]):
        for i in range(A.shape[0]):
            if i+l < A.shape[0]:
                if A[i+l,j] != 0:
                    elementary_ops_interchange_rows(A,i+l+1,l+1)
                    print(A)
                    sweep_out_col(A,j+1,(l+1,j+1))
                    print(A)
                    l = l+1 
                    
    
        
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
        
    return A 

np.random.seed(42)# for reproduce the random numbers
n = 5
m = 5
A = np.random.randint(-2,2,size=(5,5))
print('A random matrices A:\n{}' .format(A))
print('-'*70)

UT_A = reduced_identity_form(A)        
print('The reduced identity form of A:\n{} ' .format(np.round(UT_A, 3)))
print('-'*70)      


A random matrices A:
[[ 0  1 -2  0  0]
 [ 1 -2 -2  0 -1]
 [ 0  0  0  0  1]
 [-2  1  1  1  0]
 [-1 -2 -1  1  1]]
----------------------------------------------------------------------
[[ 1 -2 -2  0 -1]
 [ 0  1 -2  0  0]
 [ 0  0  0  0  1]
 [-2  1  1  1  0]
 [-1 -2 -1  1  1]]
[[ 1 -2 -2  0 -1]
 [ 0  1 -2  0  0]
 [ 0  0  0  0  1]
 [ 0 -3 -3  1 -2]
 [ 0 -4 -3  1  0]]
[[ 1 -2 -2  0 -1]
 [ 0  1 -2  0  0]
 [ 0  0  0  0  1]
 [ 0 -3 -3  1 -2]
 [ 0 -4 -3  1  0]]
[[  1   0  -6   0  -1]
 [  0   1  -2   0   0]
 [  0   0   0   0   1]
 [  0   0  -9   1  -2]
 [  0   0 -11   1   0]]
[[  1   0  -6   0  -1]
 [  0   1  -2   0   0]
 [  0   0  -9   1  -2]
 [  0   0   0   0   1]
 [  0   0 -11   1   0]]
[[ 1  0  0  0 -1]
 [ 0  1  0  0  0]
 [ 0  0  1  0  0]
 [ 0  0  0  0  1]
 [ 0  0  0  1  0]]
[[ 1  0  0  0 -1]
 [ 0  1  0  0  0]
 [ 0  0  1  0  0]
 [ 0  0  0  1  0]
 [ 0  0  0  0  1]]
[[ 1  0  0  0 -1]
 [ 0  1  0  0  0]
 [ 0  0  1  0  0]
 [ 0  0  0  1  0]
 [ 0  0  0  0  1]]
[[ 1  0  0  0 -1]
 [ 0  1  0  0  0]
 [ 